[project]
name = "ratingrelay"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.12",
    "liblistenbrainz>=0.5.6",
    "musicbrainzngs>=0.7.1",
    "pylast~=5.3.0",
    "python-dotenv~=1.0.1",
    "requests~=2.32.3",
    "xmltodict~=0.14.2",
]
